# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
